package com.metrobg.netmanager.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _HostInterfaces was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _HostInterfaces extends CayenneDataObject {

    private static final long serialVersionUID = 1L;

    public static final String CUSTOMER_ID_PK_COLUMN = "CUSTOMER_ID";
    public static final String DEVICE_TYPE_ID_PK_COLUMN = "DEVICE_TYPE_ID";
    public static final String HOST_ID_PK_COLUMN = "HOST_ID";
    public static final String INTERFACE_ID_PK_COLUMN = "INTERFACE_ID";

    public static final Property<String> DNS_ARECORD = Property.create("dnsARecord", String.class);
    public static final Property<String> INTERFACE_IP_ADDRESS = Property.create("interfaceIpAddress", String.class);
    public static final Property<String> INTERFACE_NAME = Property.create("interfaceName", String.class);
    public static final Property<String> INTERFACE_TYPE = Property.create("interfaceType", String.class);
    public static final Property<Integer> NETWORK_DEVICE_DEVICE_TYPE_ID = Property.create("networkDeviceDeviceTypeId", Integer.class);

    public void setDnsARecord(String dnsARecord) {
        writeProperty("dnsARecord", dnsARecord);
    }

    public String getDnsARecord() {
        return (String) readProperty("dnsARecord");
    }

    public void setInterfaceIpAddress(String interfaceIpAddress) {
        writeProperty("interfaceIpAddress", interfaceIpAddress);
    }

    public String getInterfaceIpAddress() {
        return (String) readProperty("interfaceIpAddress");
    }

    public void setInterfaceName(String interfaceName) {
        writeProperty("interfaceName", interfaceName);
    }

    public String getInterfaceName() {
        return (String) readProperty("interfaceName");
    }

    public void setInterfaceType(String interfaceType) {
        writeProperty("interfaceType", interfaceType);
    }

    public String getInterfaceType() {
        return (String) readProperty("interfaceType");
    }

    public void setNetworkDeviceDeviceTypeId(int networkDeviceDeviceTypeId) {
        writeProperty("networkDeviceDeviceTypeId", networkDeviceDeviceTypeId);
    }

    public int getNetworkDeviceDeviceTypeId() {
        Object value = readProperty("networkDeviceDeviceTypeId");
        return (value != null) ? (Integer) value : 0;
    }

}
