package com.metrobg.netmanager.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _HostServices was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _HostServices extends CayenneDataObject {

    private static final long serialVersionUID = 1L;

    public static final String CUSTOMER_ID_PK_COLUMN = "CUSTOMER_ID";
    public static final String DEVICE_TYPE_ID_PK_COLUMN = "DEVICE_TYPE_ID";
    public static final String HOST_ID_PK_COLUMN = "HOST_ID";
    public static final String SERVICE_ID_PK_COLUMN = "SERVICE_ID";

    public static final Property<Integer> NETWORK_DEVICE_DEVICE_TYPE_ID = Property.create("networkDeviceDeviceTypeId", Integer.class);

    public void setNetworkDeviceDeviceTypeId(int networkDeviceDeviceTypeId) {
        writeProperty("networkDeviceDeviceTypeId", networkDeviceDeviceTypeId);
    }

    public int getNetworkDeviceDeviceTypeId() {
        Object value = readProperty("networkDeviceDeviceTypeId");
        return (value != null) ? (Integer) value : 0;
    }

}
