package com.metrobg.netmanager.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.metrobg.netmanager.persistent.NetworkDevice;

/**
 * Class _OsType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _OsType extends CayenneDataObject {

    private static final long serialVersionUID = 1L;

    public static final String OS_ID_PK_COLUMN = "OS_ID";

    public static final Property<String> OS_NAME = Property.create("osName", String.class);
    public static final Property<List<NetworkDevice>> NETWORK_DEVICES = Property.create("networkDevices", List.class);

    public void setOsName(String osName) {
        writeProperty("osName", osName);
    }

    public String getOsName() {
        return (String) readProperty("osName");
    }

    public void addToNetworkDevices(NetworkDevice obj) {
        addToManyTarget("networkDevices", obj, true);
    }

    public void removeFromNetworkDevices(NetworkDevice obj) {
        removeToManyTarget("networkDevices", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<NetworkDevice> getNetworkDevices() {
        return (List<NetworkDevice>) readProperty("networkDevices");
    }


}
