package com.metrobg.netmanager.persistent.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _States was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _States extends CayenneDataObject {

    private static final long serialVersionUID = 1L;

    public static final String STATE_ID_PK_COLUMN = "STATE_ID";

    public static final Property<String> STATE_NAME = Property.create("stateName", String.class);

    public void setStateName(String stateName) {
        writeProperty("stateName", stateName);
    }

    public String getStateName() {
        return (String) readProperty("stateName");
    }

}
